### ISSUE TITLE
version check doesn't use org-babel-command 

### ISSUE THREAD

**Issue by ErikaKuykendall** [lurdan/ob-typescript#7]
https://github.com/lurdan/ob-typescript/blob/abf36f1f3b2476e71c63721dc907d7e6914aef3d/ob-typescript.el#L65

get-tsc-version hardcodes a call to tsc rather than using the user-configurable org-babel-command:typescript, which breaks the ability to use the package without globally installing typescript

**Comment by lurdan** [comment]
lgtm, thanks.
